
Requete 1 :
import fichier df_200x2iter.csv
import fichier chunks.csv
import fichier concerts.csv


Requete 5 :
Le pourcentage de chanson dans le genre d'un artiste

Requete 6 :
le nombre d'artiste qui fait a la fois un genre et un autre genre

Requete 7 :
A partir d'un utilisateur, recuperer la liste des artistes qu'il écoute et retourner la liste des concerts dans lesquels ces artistes joue
et en retourner 30 
 
Requete 8 :
Comparaison entre le pageRank et la popularité 
